title: PPW - Web Search & Mining
author: Elvita Dian Prameswari
logo: foto.jpg

repository:
  url: https://github.com/elpitaa/PPW

exclude_patterns:
  - .venv/**
  - _build/**
  - .git/**

execute:
  execute_notebooks: off

html:
  home_page_in_navbar: true
  use_issues_button: true
  use_repository_button: true
  use_download_button: true